### PR TITLE
Build and release on  RHEL8

### PR DESCRIPTION
**Pull request by gwarf**
* Build and release on RHEL8
* Prepare version 5.1.0

### CODE REVIEW

**Comment by gwarf** [comment]
Dear @andrea-manzi, please have a look, thanks!

**Comment by andrea-manzi** [comment]
thanks a lot @gwarf, but i don't understand why we need this...UMD5 will be only for el9

**Comment by maarten-litmaath** [comment]
Hi all,
at least KIT will have WNs on EL8 for a while and could then profit from a WN and possibly a UI meta package.
That said, not all clients may be available or supported on EL8.
If it is too tricky to get things sufficiently right for EL8, we can also decide to abandon this attempt...

**Comment by gwarf** [comment]
Building the meta-packages is not difficult for us, if it helps, and the dependencies can be taken from any repo, be it UMD5 on El9, or upstream/different repo on things like EL8.

**Comment by gwarf** [comment]
@andrea-manzi can you please review this PR?
We can let the RHLE8 package available here and let people add it to/take it from whatever repo they may be using.
Or we can just close/cancel this PR.

**Review by andrea-manzi — APPROVED** [review]
@gwarf thanks! LGTM! i noticed that so far we have not included cvmfs in the el8/el9 build as it's not in EPEL..but i think it's quite needed.. @maarten-litmaath maybe you can include it in the wlcg repository ? ( we can do the change in this or a new PR then)

**Comment by maarten-litmaath** [comment]
> @gwarf thanks! LGTM! i noticed that so far we have not included cvmfs in the el8/el9 build as it's not in EPEL..but i think it's quite needed.. @maarten-litmaath maybe you can include it in the wlcg repository ? ( we can do the change in this or a new PR then)

Hi guys,
I can copy CVMFS rpms into the WLCG repo, but only for as few as possible!
I hope these are already sufficient:

cvmfs
cvmfs-config-default
cvmfs-libs

What do you think?

Shall I pick the latest of those from the CVMFS repos:

http://ecsft.cern.ch/dist/cvmfs/

?

**Comment by andrea-manzi** [comment]
> > @gwarf thanks! LGTM! i noticed that so far we have not included cvmfs in the el8/el9 build as it's not in EPEL..but i think it's quite needed.. @maarten-litmaath maybe you can include it in the wlcg repository ? ( we can do the change in this or a new PR then)
> 
> Hi guys, I can copy CVMFS rpms into the WLCG repo, but only for as few as possible! I hope these are already sufficient:
> 
> cvmfs cvmfs-config-default cvmfs-libs
> 
> What do you think?
> 
> Shall I pick the latest of those from the CVMFS repos:
> 
> http://ecsft.cern.ch/dist/cvmfs/
> 
> ?

yes perfect , thanks!

**Comment by gwarf** [comment]
I will add cvmfs to the dependencies, yes I think the latest version should be OK, like the one retrieved from the repo setup by https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm.
The other solution is to let the users set this CVMFS repo up themselves using things like `yum install https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm`.

**Comment by gwarf** [comment]
> I will add cvmfs to the dependencies, yes I think the latest version should be OK, like the one retrieved from the repo setup by https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm. The other solution is to let the users set this CVMFS repo up themselves using things like `yum install https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm`.

It's what I will do for building/testing in the GitHub action.  (And currently the WLCG repo is not used in this action)

**Comment by gwarf** [comment]
@maarten-litmaath please let me know if now this looks OK to you, and I will merge and release the new version.

**Comment by maarten-litmaath** [comment]
Hi all,
the WLCG repo now contains cvmfs-2.11.3 and cvmfs-config-default-2.0-1, as used in production at CERN and presumably at many other sites already.  The rpms are present for EL8 and EL9.

**Comment by maarten-litmaath** [comment]
Hi again,
I have installed an EL8 UI OK using ui-6.1.0-1.el8.

**Comment by maarten-litmaath** [comment]
Note: ui-6.1.0 is not published (yet) in the WLCG repository, because you would still want to add CVMFS as a dependency, right?

**Comment by gwarf** [comment]
> Note: ui-6.1.0 is not published (yet) in the WLCG repository, because you would still want to add CVMFS as a dependency, right?

The UI metapackage never contained cvmfs, and indeed we can add it.
We have been doing a bit too much of cross discussions between the repos, and sometimes I get confused :) Let's try to follow here only on the WN and us PR or create issue to discuss in the ui-metapackage repo.
I will merge this PR and release a new wn-metapackage, and open a PR to add cvmfs to the UI metapackage.

**Comment by gwarf** [comment]
Latest (hopefully 😅 ) release: https://github.com/EGI-Federation/wn-metapackage/releases/tag/v5.1.0

**Comment by gwarf** [comment]
> Note: ui-6.1.0 is not published (yet) in the WLCG repository, because you would still want to add CVMFS as a dependency, right?

In case you are not watching the ui-metapackage repo, here is a new version: https://github.com/EGI-Federation/ui-metapackage/releases/tag/v6.2.0

**Comment by maarten-litmaath** [comment]
Hi again,
wn-5.1.0 has been tested for EL8 and EL9 and is published now:

https://linuxsoft.cern.ch/wlcg/

I note the EL8 rpm has the complete (?) change log,
while the EL9 rpm only has a truncated version:
perhaps something to look into for the next version?

**Comment by maarten-litmaath** [comment]
Hi again,
ui-6.2.0 has also been tested on EL8 and EL9 and is also published now:

https://linuxsoft.cern.ch/wlcg/

There are the same observations regarding the change logs.

**Comment by gwarf** [comment]
> Hi again, wn-5.1.0 has been tested for EL8 and EL9 and is published now:
> 
> https://linuxsoft.cern.ch/wlcg/
> 
> I note the EL8 rpm has the complete (?) change log, while the EL9 rpm only has a truncated version: perhaps something to look into for the next version?

I'm not sure to get exactly what is missing/where, can you please document and record this in an issue?

**Comment by maarten-litmaath** [comment]
Hi again,
just run "rpm -qp --changelog" on each rpm and you will see...
Not a big deal, though.

**Comment by gwarf** [comment]
> rpm -qp --changelog

Interesting, it may be due to https://bugzilla.redhat.com/show_bug.cgi?id=1722806#c1

I'm not too concerned, but if you think we should fix this please open an issue :)

**Comment by maarten-litmaath** [comment]
Not important enough...   :-)

**Pull request merged**
